.PHONY: clean All

All:
	@echo "----------Building project:[ 02_FunctionTemplate - Debug ]----------"
	@cd "02_FunctionTemplate" && "$(MAKE)" -f  "02_FunctionTemplate.mk"
clean:
	@echo "----------Cleaning project:[ 02_FunctionTemplate - Debug ]----------"
	@cd "02_FunctionTemplate" && "$(MAKE)" -f  "02_FunctionTemplate.mk" clean
