.PHONY: clean All

All:
	@echo "----------Building project:[ 01_STL - Debug ]----------"
	@cd "01_STL" && "$(MAKE)" -f  "01_STL.mk"
clean:
	@echo "----------Cleaning project:[ 01_STL - Debug ]----------"
	@cd "01_STL" && "$(MAKE)" -f  "01_STL.mk" clean
