.PHONY: clean All

All:
	@echo "----------Building project:[ Mystring-start - Debug ]----------"
	@cd "Project1" && "$(MAKE)" -f  "Mystring-start.mk"
clean:
	@echo "----------Cleaning project:[ Mystring-start - Debug ]----------"
	@cd "Project1" && "$(MAKE)" -f  "Mystring-start.mk" clean
