.PHONY: clean All

All:
	@echo "----------Building project:[ NestedIfelse - Debug ]----------"
	@cd "NestedIfelse" && "$(MAKE)" -f  "NestedIfelse.mk"
clean:
	@echo "----------Cleaning project:[ NestedIfelse - Debug ]----------"
	@cd "NestedIfelse" && "$(MAKE)" -f  "NestedIfelse.mk" clean
