.PHONY: clean All

All:
	@echo "----------Building project:[ VectorAccessingModifyingElts - Debug ]----------"
	@cd "VectorAccessingModifyingElts" && "$(MAKE)" -f  "VectorAccessingModifyingElts.mk"
clean:
	@echo "----------Cleaning project:[ VectorAccessingModifyingElts - Debug ]----------"
	@cd "VectorAccessingModifyingElts" && "$(MAKE)" -f  "VectorAccessingModifyingElts.mk" clean
