.PHONY: clean All

All:
	@echo "----------Building project:[ PassingPointerAsFunctionParameter - Debug ]----------"
	@cd "PassingPointerAsFunctionParameter" && "$(MAKE)" -f  "PassingPointerAsFunctionParameter.mk"
clean:
	@echo "----------Cleaning project:[ PassingPointerAsFunctionParameter - Debug ]----------"
	@cd "PassingPointerAsFunctionParameter" && "$(MAKE)" -f  "PassingPointerAsFunctionParameter.mk" clean
