.PHONY: clean All

All:
	@echo "----------Building project:[ Cpp_string - Debug ]----------"
	@cd "Cpp_string" && "$(MAKE)" -f  "Cpp_string.mk"
clean:
	@echo "----------Cleaning project:[ Cpp_string - Debug ]----------"
	@cd "Cpp_string" && "$(MAKE)" -f  "Cpp_string.mk" clean
