.PHONY: clean All

All:
	@echo "----------Building project:[ Function_eg - Debug ]----------"
	@cd "Function_eg" && "$(MAKE)" -f  "Function_eg.mk"
clean:
	@echo "----------Cleaning project:[ Function_eg - Debug ]----------"
	@cd "Function_eg" && "$(MAKE)" -f  "Function_eg.mk" clean
