.PHONY: clean All

All:
	@echo "----------Building project:[ 01_Mystring-start - Debug ]----------"
	@cd "01_Mystring-start" && "$(MAKE)" -f  "01_Mystring-start.mk"
clean:
	@echo "----------Cleaning project:[ 01_Mystring-start - Debug ]----------"
	@cd "01_Mystring-start" && "$(MAKE)" -f  "01_Mystring-start.mk" clean
